In [1]:
import pandas as pd

# import data

In [2]:
# area_spm = pd.read_csv('C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/area_SPM_time_series_cota.csv').drop(columns=['Unnamed: 0'])
# precipitation = pd.read_csv('C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/mean_precip_acum_cota.csv')
# discharge = pd.read_csv('C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/mean_watershed_discharge_cota.csv').drop(columns=['Unnamed: 0'])
# wind = pd.read_csv('C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/mean_watershed_wind_cota.csv')

area_spm = pd.read_csv('C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/area_SPM_time_series_cota.csv').drop(columns=['Unnamed: 0'])
precipitation = pd.read_csv('C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/mean_precip_acum_cota.csv')
discharge = pd.read_csv('C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/mean_watershed_discharge_cota.csv').drop(columns=['Unnamed: 0'])
wind = pd.read_csv('C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/mean_watershed_wind_cota.csv')

In [3]:
# precipitation_n2 = pd.read_csv('C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/mean_precip_acum_cotaN2.csv')
# wind_n2 = pd.read_csv('C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/mean_watershed_wind_cotaN2.csv')

precipitation_n2 = pd.read_csv('C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/mean_precip_acum_cotaN2.csv')
wind_n2 = pd.read_csv('C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/mean_watershed_wind_cotaN2.csv')

# organize dataframes

In [4]:
print('colunms area', area_spm.columns)
print('colunms precipitation', precipitation.columns)
print('colunms discharge', discharge.columns)
print('colunms wind', wind.columns)

colunms area Index(['area_km2', 'mean_SPM', 'max_SPM', 'min_SPM', 'stdDev_SPM',
       'time_finish', 'time_start', 'year', 'WATER_PERIOD'],
      dtype='object')
colunms precipitation Index(['mean_precipitation', 'month_end', 'month_init', 'time_finish',
       'time_start', 'year'],
      dtype='object')
colunms discharge Index(['water_period', 'media_vazao', 'Data', 'type', 'day', 'month', 'year',
       'longitude', 'latitude', 'time_start'],
      dtype='object')
colunms wind Index(['mean_u__wind', 'mean_v__wind', 'month_end', 'month_init',
       'time_finish', 'time_start', 'year'],
      dtype='object')

In [5]:
print('colunms area', precipitation_n2.columns)
print('colunms precipitation', wind_n2.columns)

colunms area Index(['mean_precipitation', 'month_end', 'month_init', 'time_finish',
       'time_start', 'year'],
      dtype='object')
colunms precipitation Index(['mean_u__wind', 'mean_v__wind', 'month_end', 'month_init',
       'time_finish', 'time_start', 'year'],
      dtype='object')

In [6]:
area_spm = area_spm[['area_km2', 'mean_SPM', 'max_SPM', 'min_SPM', 'stdDev_SPM',
       'time_start', 'year', 'WATER_PERIOD']].copy()
precipitation = precipitation[['mean_precipitation', 
       'time_start', 'year']].copy()
discharge = discharge[['media_vazao',  'year',
       'time_start']].copy()
wind = wind[['mean_u__wind', 'mean_v__wind', 
       'time_finish', 'time_start', 'year']].copy()

precipitation_n2 = precipitation_n2[['mean_precipitation', 
       'time_start', 'year']].copy()
wind_n2 = wind_n2[['mean_u__wind', 'mean_v__wind', 
       'time_finish', 'time_start', 'year']].copy()

In [7]:
area_spm.columns = ['area_km2', 'mean_SPM', 'max_SPM', 'min_SPM', 'stdDev_SPM', 
        'time_start', 'year', 'water_period']
precipitation.columns = ['mean_precipitation', 'time_start', 'year']
discharge.columns = [ 'mean_discharge',  'year',
       'time_start']
wind.columns = ['mean_u__wind', 'mean_v__wind', 
       'time_finish', 'time_start', 'year']

precipitation_n2.columns = ['mean_precipitation', 'time_start', 'year']
wind_n2.columns = ['mean_u__wind', 'mean_v__wind', 
       'time_finish', 'time_start', 'year']

In [6]:
# def add_period(row):
#     if row['month_init'] == 1 or row['month_init']== 2 or row['month_init'] == 3:
#         val = 'R'
#     elif row['month_init'] == 4 or row['month_init'] == 5 or row['month_init'] == 6:
#         val = 'HW'
#     elif row['month_init'] == 7 or row['month_init'] == 8 or row['month_init'] == 9:
#         val = 'F'
#     else:
#         val = 'LW'
#     return val

# precipitation['water_period'] = precipitation.apply(add_period, axis=1)
# wind['water_period'] = wind.apply(add_period, axis=1)

# merge dataframes

In [8]:
precipitation_n2

     mean_precipitation  time_start  year
0            283.192410  1990-01-18  1990
1           1311.143081  1990-02-23  1990
2             74.809668  1990-08-06  1990
3            304.228764  1990-09-09  1990
4            561.373218  1990-12-22  1990
..                  ...         ...   ...
125           39.496524  2023-08-01  2023
126          849.509686  2023-08-25  2023
127          103.628712  2024-03-25  2024
128          605.589208  2024-04-06  2024
129          680.934636  2024-05-30  2024

[130 rows x 3 columns]

In [9]:
precipitation

     mean_precipitation  time_start  year
0            272.137999  1990-01-18  1990
1           1090.293867  1990-02-23  1990
2             40.262010  1990-08-06  1990
3            252.061898  1990-09-09  1990
4            753.009833  1990-12-22  1990
..                  ...         ...   ...
125           11.183049  2023-08-01  2023
126         1029.686248  2023-08-25  2023
127           98.192707  2024-03-25  2024
128          738.124573  2024-04-06  2024
129          526.185253  2024-05-30  2024

[130 rows x 3 columns]

In [10]:
df_pt1 =  pd.merge(area_spm, precipitation, how="left", on=["time_start", "year"])
df_pt1_n2 =  pd.merge(area_spm, precipitation_n2, how="left", on=["time_start", "year"])
df_pt1_n2

,area_km2,mean_SPM,max_SPM,min_SPM,stdDev_SPM,time_start,year,water_period,mean_precipitation
0,821.581875,185.751681,306.049042,6.048137,75.431006,1990-01-18,1990,R,283.192410
1,1328.106533,35.795486,220.133545,5.868872,20.544100,1990-02-23,1990,HW,1311.143081
2,1177.990137,27.310809,282.490112,5.868872,20.916411,1990-08-06,1990,F,74.809668
3,1042.613269,126.406865,306.049042,5.929328,70.059463,1990-09-09,1990,LW,304.228764
4,1047.897172,58.323214,298.301147,5.939963,39.882937,1990-12-22,1990,R,561.373218
...,...,...,...,...,...,...,...,...,...
103,1428.350797,26.464622,298.301147,5.801264,12.778907,2023-08-01,2023,F,39.496524
104,818.725543,101.950881,296.378998,6.048137,70.378524,2023-08-25,2023,R,849.509686
105,1082.838632,45.593203,304.234253,5.972806,22.119043,2024-03-25,2024,HW,103.628712
106,1185.061555,38.188542,282.490112,5.510151,23.110245,2024-04-06,2024,F,605.589208
107,1184.201748,46.784273,257.671570,5.674996,33.440110,2024-05-30,2024,LW,680.934636

In [11]:
df_pt2 =  pd.merge(discharge, wind, how="outer", on=["time_start", "year"])
df_pt2_n2 =  pd.merge(discharge, wind_n2, how="outer", on=["time_start", "year"])
df_pt2

     mean_discharge  year  time_start  mean_u__wind  mean_v__wind time_finish
0     132135.749286  1990  1990-01-18     -1.395180     -0.548752  1990-02-23
1     178324.683893  1990  1990-02-23     -1.642547     -0.090854  1990-08-06
2     165665.867255  1990  1990-08-06     -1.714281      0.369884  1990-09-09
3     109090.802714  1990  1990-09-09     -1.804203      0.117485  1990-12-22
4     159619.042703  1990  1990-12-22     -1.667687     -0.624494  1991-03-01
..              ...   ...         ...           ...           ...         ...
125   180788.903056  2023  2023-08-01     -2.054332     -0.283952  2023-08-25
126   118005.620148  2023  2023-08-25     -2.029501     -0.194141  2024-03-25
127   169781.068387  2024  2024-03-25     -1.369804     -0.202571  2024-04-06
128   203966.253077  2024  2024-04-06     -1.321464     -0.266093  2024-05-30
129   129132.978647  2024  2024-05-30     -1.907889     -0.324219  2025-01-01

[130 rows x 6 columns]

In [12]:
df_total = pd.merge(df_pt1, df_pt2, how="left", on=["time_start", "year"])
df_total_n2 = pd.merge(df_pt1_n2, df_pt2_n2, how="left", on=["time_start", "year"])
df_total_n2

,area_km2,mean_SPM,max_SPM,min_SPM,stdDev_SPM,time_start,year,water_period,mean_precipitation,mean_discharge,mean_u__wind,mean_v__wind,time_finish
0,821.581875,185.751681,306.049042,6.048137,75.431006,1990-01-18,1990,R,283.192410,132135.749286,-0.757564,-0.642454,1990-02-23
1,1328.106533,35.795486,220.133545,5.868872,20.544100,1990-02-23,1990,HW,1311.143081,178324.683893,-0.805459,-0.196663,1990-08-06
2,1177.990137,27.310809,282.490112,5.868872,20.916411,1990-08-06,1990,F,74.809668,165665.867255,-0.681016,0.073830,1990-09-09
3,1042.613269,126.406865,306.049042,5.929328,70.059463,1990-09-09,1990,LW,304.228764,109090.802714,-0.720925,-0.121658,1990-12-22
4,1047.897172,58.323214,298.301147,5.939963,39.882937,1990-12-22,1990,R,561.373218,159619.042703,-1.016738,-0.671618,1991-03-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,1428.350797,26.464622,298.301147,5.801264,12.778907,2023-08-01,2023,F,39.496524,180788.903056,-1.003614,-0.272865,2023-08-25
104,818.725543,101.950881,296.378998,6.048137,70.378524,2023-08-25,2023,R,849.509686,118005.620148,-1.131968,-0.327666,2024-03-25
105,1082.838632,45.593203,304.234253,5.972806,22.119043,2024-03-25,2024,HW,103.628712,169781.068387,-0.806059,-0.214633,2024-04-06
106,1185.061555,38.188542,282.490112,5.510151,23.110245,2024-04-06,2024,F,605.589208,203966.253077,-0.645302,-0.148800,2024-05-30
107,1184.201748,46.784273,257.671570,5.674996,33.440110,2024-05-30,2024,LW,680.934636,129132.978647,-0.978633,-0.252284,2025-01-01

In [13]:
# df_total.to_csv('C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/merged_df/df_merged_cota.csv')
# df_total_n2.to_csv('C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/merged_df/df_merged_cotaN2.csv')

df_total.to_csv('C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/merged_df/df_merged_cota.csv')
df_total_n2.to_csv('C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/merged_df/df_merged_cotaN2.csv')

# include lulc data

In [14]:
# lulc = pd.read_csv("C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/lulc_curuai.csv").drop(columns=['band','class'])
lulc = pd.read_csv("C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/lulc_curuai.csv").drop(columns=['band','class'])
        
lulc= lulc.loc[lulc['class_name'] == 'Non-natural'].copy()
lulc.columns = ['year', 'anthropic_km2', 'class_name']
lulc

    year  anthropic_km2   class_name
34  1990    2754.992235  Non-natural
35  1991    2797.399913  Non-natural
36  1992    3115.773735  Non-natural
37  1993    3332.313777  Non-natural
38  1994    3465.716377  Non-natural
39  1995    3627.713376  Non-natural
40  1996    3851.459413  Non-natural
41  1997    4334.899090  Non-natural
42  1998    4798.819817  Non-natural
43  1999    4949.456143  Non-natural
44  2000    4965.635665  Non-natural
45  2001    5063.954651  Non-natural
46  2002    5021.247566  Non-natural
47  2003    5229.852382  Non-natural
48  2004    5502.955202  Non-natural
49  2005    5841.827715  Non-natural
50  2006    6003.141167  Non-natural
51  2007    5973.413145  Non-natural
52  2008    6052.845250  Non-natural
53  2009    6319.366469  Non-natural
54  2010    6296.563494  Non-natural
55  2011    6165.935573  Non-natural
56  2012    6030.065870  Non-natural
57  2013    6240.115456  Non-natural
58  2014    6451.345538  Non-natural
59  2015    6676.036989  Non-natural
60  2016    6819.203556  Non-natural
61  2017    6852.859372  Non-natural
62  2018    6734.515507  Non-natural
63  2019    6581.596972  Non-natural
64  2020    6688.082816  Non-natural
65  2021    6708.529970  Non-natural
66  2022    7027.440277  Non-natural
67  2023    7525.813345  Non-natural

In [15]:
# lulc_n2 = pd.read_csv("C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/lulc_curuaiN2.csv").drop(columns=['band','class'])
lulc_n2 = pd.read_csv("C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/lulc_curuaiN2.csv").drop(columns=['band','class'])
        
lulc_n2= lulc_n2.loc[lulc_n2['class_name'] == 'Non-natural'].copy()
lulc_n2.columns = ['year', 'anthropic_km2', 'class_name']
lulc_n2

    year  anthropic_km2   class_name
34  1990    2799.696772  Non-natural
35  1991    2846.756608  Non-natural
36  1992    3167.753270  Non-natural
37  1993    3385.264356  Non-natural
38  1994    3519.960664  Non-natural
39  1995    3681.940047  Non-natural
40  1996    3907.185912  Non-natural
41  1997    4397.343853  Non-natural
42  1998    4862.478890  Non-natural
43  1999    5011.971434  Non-natural
44  2000    5046.492623  Non-natural
45  2001    5152.010545  Non-natural
46  2002    5152.973198  Non-natural
47  2003    5367.898128  Non-natural
48  2004    5646.567402  Non-natural
49  2005    5989.936162  Non-natural
50  2006    6156.059964  Non-natural
51  2007    6132.546715  Non-natural
52  2008    6217.090398  Non-natural
53  2009    6491.272837  Non-natural
54  2010    6471.343676  Non-natural
55  2011    6347.324258  Non-natural
56  2012    6219.623145  Non-natural
57  2013    6437.910765  Non-natural
58  2014    6657.368752  Non-natural
59  2015    6894.195028  Non-natural
60  2016    7049.035263  Non-natural
61  2017    7095.971593  Non-natural
62  2018    6987.510519  Non-natural
63  2019    6844.993531  Non-natural
64  2020    6964.110026  Non-natural
65  2021    7015.770744  Non-natural
66  2022    7356.688479  Non-natural
67  2023    7855.059223  Non-natural

In [16]:
df_lulc = df_total.merge(lulc,on='year',how='outer')
df_lulc_n2 = df_total_n2.merge(lulc_n2,on='year',how='outer')
df_lulc_n2

,area_km2,mean_SPM,max_SPM,min_SPM,stdDev_SPM,time_start,year,water_period,mean_precipitation,mean_discharge,mean_u__wind,mean_v__wind,time_finish,anthropic_km2,class_name
0,821.581875,185.751681,306.049042,6.048137,75.431006,1990-01-18,1990,R,283.192410,132135.749286,-0.757564,-0.642454,1990-02-23,2799.696772,Non-natural
1,1328.106533,35.795486,220.133545,5.868872,20.544100,1990-02-23,1990,HW,1311.143081,178324.683893,-0.805459,-0.196663,1990-08-06,2799.696772,Non-natural
2,1177.990137,27.310809,282.490112,5.868872,20.916411,1990-08-06,1990,F,74.809668,165665.867255,-0.681016,0.073830,1990-09-09,2799.696772,Non-natural
3,1042.613269,126.406865,306.049042,5.929328,70.059463,1990-09-09,1990,LW,304.228764,109090.802714,-0.720925,-0.121658,1990-12-22,2799.696772,Non-natural
4,1047.897172,58.323214,298.301147,5.939963,39.882937,1990-12-22,1990,R,561.373218,159619.042703,-1.016738,-0.671618,1991-03-01,2799.696772,Non-natural
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,1428.350797,26.464622,298.301147,5.801264,12.778907,2023-08-01,2023,F,39.496524,180788.903056,-1.003614,-0.272865,2023-08-25,7855.059223,Non-natural
104,818.725543,101.950881,296.378998,6.048137,70.378524,2023-08-25,2023,R,849.509686,118005.620148,-1.131968,-0.327666,2024-03-25,7855.059223,Non-natural
105,1082.838632,45.593203,304.234253,5.972806,22.119043,2024-03-25,2024,HW,103.628712,169781.068387,-0.806059,-0.214633,2024-04-06,NaN,NaN
106,1185.061555,38.188542,282.490112,5.510151,23.110245,2024-04-06,2024,F,605.589208,203966.253077,-0.645302,-0.148800,2024-05-30,NaN,NaN
107,1184.201748,46.784273,257.671570,5.674996,33.440110,2024-05-30,2024,LW,680.934636,129132.978647,-0.978633,-0.252284,2025-01-01,NaN,NaN

In [17]:
# df_lulc.to_csv('C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/merged_df/df_merged_cota_lulc.csv')
# df_lulc_n2.to_csv('C:/Users/l_v_v/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/merged_df/df_merged_cota_lulcN2.csv')

df_lulc.to_csv('C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/merged_df/df_merged_cota_lulc.csv')
df_lulc_n2.to_csv('C:/Users/LarissaVieiraValadão/Documents/GitHub/time_series_curuai/datasets/Parameters Time series/merged_df/df_merged_cota_lulcN2.csv')